---
title: "Projects"
description: |
  Here you can find an overview of my projects.
listing:
  - id: publichealth
    max-description-length: 500
    image-height: 150px
    fields: [image, title, description]
    contents: 
      - projects/csids
      - projects/phtools
      - projects/sykdomspulsen
    type: grid
    grid-item-border: false
---



## Data science in Public Health

I joined the Norwegian Institute of Public Health in 2020, as a member of the Sykdomspulsen team. We are a core part of the COVID-19 pandemic response task force in Norway. I help build the real-time public health surveillance platform using R and other open source data science tools. You can find our R packages [here](https://github.com/sykdomspulsen-org).

In 2021-2022, I am the responsible statistician for NorMOMO, the Norwegian Mortality Monitoring project, which is part of the European network EuroMOMO. I work on R packages [nowcast](https://docs.sykdomspulsen.no/nowcast/) and [splalert](https://docs.sykdomspulsen.no/splalert/).

::: {#publichealth}
:::


## Research

I have earned my PhD from University of Oslo in 2022. My PhD research was on the representation and utilization of hospital electronic health records data.

## Advising

I work as a statistical advisor on the side, helping clinical researchers with methodology and anaysis.

